name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          plugins: poetry-dynamic-versioning[plugin]

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4.2.0
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Install root package only
        if: steps.cached-poetry-dependencies.outputs.cache-hit == 'true'
        run: poetry install --no-interaction --only-root

      - name: Build package
        run: |
          poetry build

      - name: Generate changelog for latest tag
        uses: orhun/git-cliff-action@v4.4.2
        with:
          config: cliff.toml
          args: --latest
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      # - name: Create release
      #   uses: softprops/action-gh-release@v2.1.0
      #   with:
      #     files: dist/*
      #     body_path: CHANGELOG.md

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          repository-url: https://test.pypi.org/legacy/
